# Makefile for cs 455 C++ Debugger / Linked lists lab


factors: factors.cpp
	g++ -ggdb -Wall factors.cpp -o factors

testlist: testlist.cpp
	g++ -ggdb -Wall testlist.cpp -o testlist

submit:
	submit -user csci455 -tag lab12 README factors.cpp testlist.cpp
